apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: usersservice
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_URI
              value: {{ .Values.ldap.uri }}
            - name: LDAP_BASE
              value: {{ .Values.ldap.base }}
            - name: LDAP_DN
              value: {{ .Values.ldap.dn }}
            - name: LDAP_PASSWORD
{{- if .Values.ldap.password.password }}
              value: "{{ .Values.ldap.password.password }}"
{{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ldap.password.secret }}
                  key: {{ .Values.ldap.password.key }}
{{- end }}
            - name: APIGATEWAY_URL
              value: {{ .Values.endpoints.apigateway }}
            - name: AUTHSERVICE_ENDPOINT
              value: "https://{{ .Values.global.domain }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /users/
              port: http
          readinessProbe:
            httpGet:
              path: /users/
              port: http
